FROM node:10.5.0

# RUN git clone https://github.com/acashmkj/SecuBit.git /secubitwallet
COPY . /secubitwallet

WORKDIR /secubitwallet

RUN npm install
RUN npm run babel
RUN npm run build

EXPOSE 8081
EXPOSE 443
EXPOSE 80

CMD ["npm", "run", "server"]
